//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBfirst
{
    using System;
    
    public enum CourseLevel : byte
    {
        basic = 1,
        intermediate = 2,
        advanced = 3
    }
}
